# See https://docs.aspect.build/workflows/configuration
workspaces:
    .:
        icon: webpack
        label: rules_webpack
    e2e/loaders:
        icon: bazel
        tasks: &e2e_tasks
            - test:
                  queue: aspect-medium
            - buildifier:
                  without: true
    e2e/loaders_jslib:
        icon: bazel
        tasks: *e2e_tasks
    e2e/smoke:
        icon: bazel
        tasks: *e2e_tasks
    e2e/worker:
        icon: bazel
        tasks: *e2e_tasks
bazel:
    flags:
        - --config=ci
tasks:
    - checkout:
          update_strategy: rebase
    - test:
          name: Bazel 7
          id: bazel-7
          bazel:
              flags: ['--test_tag_filters=-skip-on-bazel7']
          env:
              USE_BAZEL_VERSION: '7.x'
    - test:
          name: Bazel 8
          id: bazel-8
          bazel:
              flags: ['--test_tag_filters=-skip-on-bazel8']
          env:
              USE_BAZEL_VERSION: '8.x'
    - test:
          name: Bazel 9
          id: bazel-9
          bazel:
              flags: ['--test_tag_filters=-skip-on-bazel9']
          env:
              USE_BAZEL_VERSION: '9.x'
    - buildifier:
          queue: aspect-medium
    - gazelle:
          queue: aspect-small
    - finalization:
          queue: aspect-small
notifications:
    github: {}
