load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

build_test(
    name = "test",
    targets = [
        "@no_rules_js//:_bundle_webpack_binary",
        "@no_rules_js//:_bundle_worker_webpack_worker_binary",
    ],
)
