workspace(
    name = "e2e",
)

# Used only so that we can load in rules_webpack_dependencies
new_local_repository(
    name = "rules_webpack",
    build_file_content = "",
    path = "../",
)

load("@rules_webpack//webpack:repositories.bzl", "rules_webpack_dependencies")

rules_webpack_dependencies()

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "npm_install")

node_repositories(
    node_version = "16.0.0",
)

npm_install(
    name = "npm",
    package_json = "//:package.json",
    package_lock_json = "//:package-lock.json",
)
