name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  # Mac/Windows smoke tests
  # Linux tests are run on Aspect Workflows (see .aspect/workflows/config.yaml)
  # Only run on main branch (not PRs) to minimize minutes (billed at 10X and 2X respectively)
  # https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes
  test:
    if: github.ref_name == 'main' || contains(github.head_ref, 'macos') || contains(github.head_ref, 'windows')
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        bzlmod: [1, 0]
        os: [macos, windows]
        folder:
          - '.'
          - 'e2e/loaders'
          - 'e2e/smoke'
          - 'e2e/smoke_rjs3'
          - 'e2e/worker'
        exclude:
          # Root repository no longer tests non-bzlmod/WORKSPACE
          - folder: .
            bzlmod: 0
          # TODO
          - folder: e2e/loaders
            bzlmod: 1
          # TODO
          - folder: e2e/worker
            bzlmod: 1
          # rules_js v3 is bzlmod-only and requires bazel 7+
          - folder: e2e/smoke_rjs3
            bzlmod: 0

    steps:
      - uses: actions/checkout@v4

      - name: Mount bazel caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel-disk-cache
            ~/.cache/bazel-repository-cache
            ~/.cache/xdg-cache
          key: bazel-cache-${{ matrix.bzlmod }}-${{ matrix.os }}-${{ matrix.folder }}-${{ hashFiles('.bazelrc', '.bazelversion', '**/BUILD', '**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', 'WORKSPACE.bazel', 'WORKSPACE.bzlmod', 'MODULE.bazel') }}
          restore-keys: bazel-cache-${{ matrix.bzlmod }}-${{ matrix.os }}-${{ matrix.folder }}-

      - name: bazel test //...
        working-directory: ${{ matrix.folder }}
        shell: bash
        run: |
          v=$(head -n 1 .bazelversion)
          m=${v::1}
          bazel \
            --bazelrc=${GITHUB_WORKSPACE//\\/\/}/tools/preset.bazelrc \
            --bazelrc=${GITHUB_WORKSPACE//\\/\/}/.github/workflows/ci.bazelrc \
            test \
            --config=ci \
            --test_tag_filters=-skip-on-bazel${m} \
            --build_tag_filters=-skip-on-bazel${m} \
            --enable_bzlmod=${{ matrix.bzlmod }} \
            //...

      - name: run ./test.sh
        working-directory: ${{ matrix.folder }}
        # hashFiles returns an empty string if test.sh is absent
        if: ${{ hashFiles(format('{0}/test.sh', matrix.folder)) != '' }}
        run: ./test.sh
